spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: HikariCP
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: appQuartzScheduler
          jobStore:
            misfireThreshold: 60000
            tablePrefix: QRTZ_
            isClustered: false
          threadPool:
            threadCount: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: AUTO

jwt:
  # Use at least 32 chars. Replace in production and consider base64-encoded string.
  secret: "change-me-please-change-me-please-change-me-please"
  issuer: "backend-scaffold"
  expiration-minutes: 120

logging:
  level:
    com.baomidou.mybatisplus: INFO
    org.springframework.security: INFO
