server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app_db
    username: app_user
    password: app_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Harden CORS settings for production as needed.
